### ISSUE TITLE
[Info] Little help from Belim 

### ISSUE THREAD

**Issue by dennyamarojr** [builtbybel/control-uwp#1]
Hi belim, 

I have contact you on twitter yesterday and it seems here on github doesn't have a DM button just issue, so, here's what I want ask you. 

I have been using your app (all of them, they are really good) and I want build some app like these one here control-uwp , I don't know if you already hear about ghost spectre Images of windows 10, they have a ghost toolbox where we can apply tweaks, download stuff, install things and modify system settings. I was thinking in create something like this but with something that has a few options like your tools does, for privacy & security.

I'm trying to create a script using cmd , and if you could help me build the app will be really awesome
Here's a pic of the main menu for you see a example
![GhostToolbox-MainMenu](https://user-images.githubusercontent.com/36896116/92637386-9f96eb80-f28d-11ea-8db9-d65f6041a471.JPG)

As you can see, has a lot of options and the user can do a lot things, if you could help , I will appreciate a lot.

Keep up the good work, belim

**Comment by Belim** [comment]
for further projects i unfortunately have no time at all. even my own projects are mostly being ignored and working on them only in the breaks and late sundays. take a look at my projects. some are very easy to program, maybe you can learn something
