### ISSUE TITLE
App Crash on Settings when using a (third-party) firewall

### ISSUE THREAD

**Issue by Velocet** [builtbybel/control-uwp#7]
When clicking on Settings the app crashes cause it can't connect to itself.

I am using WFC (https://www.binisoft.org/wfc) which blocks all outgoing request by default.

**Comment by Belim** [comment]
Yep, that fits because an update check is performed directly on call.
Should probably switch to manual check 🤔 Thanks for reporting

**Comment by Velocet** [comment]
But a manual check doesn't fix the problem and even worse:
It's always better to have auto update cause most people don't tend to update...
