### ISSUE TITLE
VirusTotal False Positive

### ISSUE THREAD

**Issue by brian6932** [builtbybel/control-uwp#9]
![image](https://user-images.githubusercontent.com/18603393/96354089-82311a80-10a0-11eb-808a-241f38617e89.png)

https://www.virustotal.com/gui/file/bf6e1ead6d8a417a74c4210e6a02708e4328fec25e1ca5557104eaa3dabb54aa/detection

**Comment by Belim** [comment]
ever heard of something security related called **Cylance** ? not me! So false garbage/positive for sure
